import type { GeneratedLifeEvent, NewsSignal } from "@/types/xtract";

export function generateScenario(signal: NewsSignal): GeneratedLifeEvent {
  const presets: Record<string, Pick<GeneratedLifeEvent, "title" | "description" | "category" | "choices">> = {
    "Auto insurance": { title: "Your Insurance Renewal Hurts", description: "Your renewal notice lands in your inbox with a higher premium. You need to decide what gives in an already tight month.", category: "Transportation", choices: [{ text: "Keep the same coverage", consequenceText: "Convenient, but the higher bill becomes part of your budget.", financialEffects: { monthlyExpenses: 53 } }, { text: "Raise your deductible", consequenceText: "You lower the premium, but take on more risk if something goes wrong.", financialEffects: { monthlyExpenses: 20, emergencyRisk: 12 } }, { text: "Shop around", consequenceText: "It takes effort, but comparison shopping could protect your cash flow.", financialEffects: { monthlyExpenses: 8 } }] },
    "Rent": { title: "Your Lease Renewal Just Arrived", description: "Your landlord gives you notice that the next lease will cost more. Moving is expensive too, so there is no effortless choice.", category: "Housing", choices: [{ text: "Renew and absorb the increase", consequenceText: "You keep stability, with less room in the monthly budget.", financialEffects: { monthlyExpenses: 125 } }, { text: "Find a roommate", consequenceText: "Sharing space cuts the hit, but changes your lifestyle.", financialEffects: { monthlyExpenses: 45 } }, { text: "Move farther out", consequenceText: "Rent falls, though the commute and moving costs rise.", financialEffects: { monthlyExpenses: 30, savings: -350 } }] },
    "Groceries": { title: "The Grocery Cart Creep", description: "Your normal grocery run costs more than it used to. This is not a one-time splurge—it is becoming a routine budget decision.", category: "Living costs", choices: [{ text: "Keep your usual routine", consequenceText: "You save time, but spend more every month.", financialEffects: { monthlyExpenses: 45 } }, { text: "Plan meals and switch stores", consequenceText: "More planning gives your budget some breathing room.", financialEffects: { monthlyExpenses: 15 } }, { text: "Use savings for convenience", consequenceText: "Your routine stays the same, but the cushion shrinks.", financialEffects: { savings: -180 } }] },
    "Borrowing": { title: "The Loan Offer Changed", description: "You are considering a purchase on credit while lending conditions are shifting. The monthly payment is only part of the real cost.", category: "Credit", choices: [{ text: "Wait and save longer", consequenceText: "You delay the purchase and avoid taking on a new payment.", financialEffects: { savings: 150 } }, { text: "Take the financing offer", consequenceText: "You get it now, but add a payment to your month.", financialEffects: { monthlyExpenses: 85, debt: 1800 } }, { text: "Choose the lower-cost option", consequenceText: "A compromise keeps your debt exposure lower.", financialEffects: { monthlyExpenses: 35, debt: 700 } }] },
    "Everyday budget": { title: "Your Monthly Budget Needs a Reset", description: "The everyday costs you counted on are creeping higher. Before the month gets away from you, you need to choose what changes.", category: "Cost of living", choices: [{ text: "Cut flexible spending", consequenceText: "You protect the essentials by trimming social and convenience spending.", financialEffects: { monthlyExpenses: 25 } }, { text: "Keep your routine", consequenceText: "Nothing changes today, but the monthly gap becomes real.", financialEffects: { monthlyExpenses: 70 } }, { text: "Build a tighter grocery and transit plan", consequenceText: "More effort now helps preserve your emergency cushion.", financialEffects: { monthlyExpenses: 35, savings: 50 } }] },
  };
  const preset = presets[signal.affectedArea] ?? presets.Borrowing;
  return { id: `scenario-${signal.id}`, ...preset, ageRange: [22, 30], newsSignalId: signal.id, sourceAttribution: { headline: signal.headline, sourceName: signal.sourceName, sourceUrl: signal.sourceUrl, publishedAt: signal.publishedAt, evidence: signal.evidence } };
}
